[package]
name = "rivet-api-public"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
axum.workspace = true
epoxy.workspace = true
futures-util.workspace = true
gas.workspace = true
include_dir.workspace = true
namespace.workspace = true
pegboard.workspace = true
reqwest.workspace = true
rivet-api-builder.workspace = true
rivet-api-peer.workspace = true
rivet-api-types.workspace = true
rivet-api-util.workspace = true
rivet-config.workspace = true
rivet-data.workspace = true
rivet-error.workspace = true
rivet-pools.workspace = true
rivet-types.workspace = true
rivet-util.workspace = true
serde_json.workspace = true
serde.workspace = true
tokio.workspace = true
tower-http.workspace = true
tracing.workspace = true
urlencoding.workspace = true
utoipa.workspace = true

[build-dependencies]
anyhow.workspace = true
fs_extra.workspace = true
