[package]
name = "rivet-workflow-worker"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
epoxy.workspace = true
gas.workspace = true
namespace.workspace = true
pegboard.workspace = true
rivet-config.workspace = true
tracing.workspace = true
