[build]
dockerfilePath = "/frontend/Dockerfile"
watchPatterns = ["/frontend/**", "/engine/sdks/typescript/**", "/rivetkit-typescript/**", "/pnpm-lock.yaml"]

[deploy]
healthcheckPath = "/health"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
