[build]
dockerfilePath = "frontend/cloud-staging.Dockerfile"
watchPatterns = ["/frontend/**", "/engine/sdks/typescript/**", "/rivetkit-typescript/**", "/pnpm-lock.yaml"]

[deploy]
healthcheckPath = "/health"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
internalPort = 80
