[build]
dockerfilePath = "frontend/ladle.Dockerfile"
watchPatterns = ["/frontend/**", "/pnpm-lock.yaml"]

[deploy]
healthcheckPath = "/health"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
internalPort = 80
