[package]
name = "pegboard"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
base64.workspace = true
bytes.workspace = true
epoxy.workspace = true
futures-util.workspace = true
gas.workspace = true
lazy_static.workspace = true
namespace.workspace = true
nix.workspace = true
rand.workspace = true
reqwest-eventsource.workspace = true
reqwest.workspace = true
rivet-api-types.workspace = true
rivet-api-util.workspace = true
rivet-config.workspace = true
rivet-data.workspace = true
rivet-error.workspace = true
rivet-metrics.workspace = true
rivet-runner-protocol.workspace = true
rivet-runtime.workspace = true
rivet-types.workspace = true
rivet-util.workspace = true
serde_bare.workspace = true
serde_json.workspace = true
serde.workspace = true
strum.workspace = true
tokio.workspace = true
tracing.workspace = true
universaldb.workspace = true
universalpubsub.workspace = true
url.workspace = true
utoipa.workspace = true
uuid.workspace = true
vbare.workspace = true

[dev-dependencies]
portpicker.workspace = true
rivet-config.workspace = true
rivet-test-deps.workspace = true
tokio.workspace = true
tracing-subscriber.workspace = true
url.workspace = true
uuid.workspace = true
