[package]
name = "rivet-api-peer"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
axum.workspace = true
base64.workspace = true
epoxy.workspace = true
epoxy-protocol.workspace = true
gas.workspace = true
indexmap.workspace = true
namespace.workspace = true
pegboard.workspace = true
pegboard-actor-kv.workspace = true
rivet-api-builder.workspace = true
rivet-api-types.workspace = true
rivet-api-util.workspace = true
rivet-config.workspace = true
rivet-error.workspace = true
rivet-pools.workspace = true
rivet-types.workspace = true
rivet-util.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tracing.workspace = true
universalpubsub.workspace = true
utoipa.workspace = true
uuid.workspace = true
