[package]
name = "rivet-metrics"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
console-subscriber.workspace = true
hyper.workspace = true
lazy_static.workspace = true
opentelemetry.workspace = true
opentelemetry-otlp.workspace = true
opentelemetry-semantic-conventions.workspace = true
opentelemetry_sdk.workspace = true
prometheus.workspace = true
rivet-config.workspace = true
rivet-env.workspace = true
tokio.workspace = true
tracing.workspace = true
