[package]
name = "pegboard-actor-kv"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
futures-util.workspace = true
gas.workspace = true
rivet-runner-protocol.workspace = true
rivet-util-id.workspace = true
serde_bare.workspace = true
serde.workspace = true
tokio.workspace = true
tracing-logfmt.workspace = true
tracing-subscriber.workspace = true
tracing.workspace = true
universaldb.workspace = true

pegboard.workspace = true

[dev-dependencies]
portpicker.workspace = true
rivet-config.workspace = true
rivet-test-deps.workspace = true
tokio.workspace = true
tracing-subscriber.workspace = true
url.workspace = true
uuid.workspace = true
