[package]
name = "rivet-guard-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
bytes.workspace = true
futures-util.workspace = true
futures.workspace = true
http-body-util.workspace = true
http-body.workspace = true
http.workspace = true
# TODO: Make this use workspace version
hyper = { version = "1.6.0", features = ["full", "http1", "http2"] }
hyper-tungstenite.workspace = true
hyper-util = { workspace = true, features = ["full"] }
indoc.workspace = true
lazy_static.workspace = true
moka = { workspace = true, features = ["future"] }
rand.workspace = true
regex.workspace = true
rivet-api-builder.workspace = true
rivet-config.workspace = true
rivet-error.workspace = true
rivet-metrics.workspace = true
rivet-runner-protocol.workspace = true
rivet-runtime.workspace = true
rivet-util.workspace = true
rustls-pemfile.workspace = true
rustls.workspace = true
serde_json.workspace = true
serde.workspace = true
tokio-rustls.workspace = true
tokio-tungstenite.workspace = true
tokio.workspace = true
tracing-opentelemetry.workspace = true
tracing-subscriber = { workspace = true, features = ["env-filter"] }
tracing.workspace = true
url.workspace = true

[dev-dependencies]
futures-util.workspace = true
futures.workspace = true
reqwest.workspace = true
tokio-stream.workspace = true
uuid.workspace = true