[package]
name = "rivet-guard"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[lib]
name = "rivet_guard"
path = "src/lib.rs"

[dependencies]
anyhow.workspace = true
axum.workspace = true
bytes.workspace = true
futures.workspace = true
gas.workspace = true
http-body-util.workspace = true
http-body.workspace = true
hyper-tungstenite.workspace = true
tower.workspace = true
# TODO: Make this use workspace version
hyper = "1.6.0"
indoc.workspace = true
lazy_static.workspace = true
once_cell.workspace = true
pegboard-gateway.workspace = true
pegboard-runner.workspace = true
pegboard.workspace = true
regex.workspace = true
rivet-api-builder.workspace = true
rivet-api-public.workspace = true
rivet-cache.workspace = true
rivet-config.workspace = true
rivet-data.workspace = true
rivet-error.workspace = true
rivet-guard-core.workspace = true
rivet-logs.workspace = true
rivet-metrics.workspace = true
rivet-pools.workspace = true
rivet-runner-protocol.workspace = true
rivet-runtime.workspace = true
rustls-pemfile.workspace = true
rustls.workspace = true
serde_json.workspace = true
serde.workspace = true
tokio-tungstenite.workspace = true
tokio.workspace = true
tracing.workspace = true
universaldb.workspace = true
universalpubsub.workspace = true
url.workspace = true
urlencoding.workspace = true
