[build]
dockerfilePath = "website/Dockerfile"
watchPatterns = ["/website/**", "/frontend/packages/**", "/examples/**", "/pnpm-lock.yaml"]

[deploy]
healthcheckPath = "/health"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
internalPort = 80
