[package]
name = "rivetkit-sqlite-vfs-native"
version = "0.0.1"
description = "Native sqlite-vfs addon for RivetKit"
edition = "2021"
license = "Apache-2.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
libsqlite3-sys = { version = "0.28.0", features = ["bundled"] }
napi = { version = "2.16.12", features = ["napi6"] }
napi-derive = "2.16.12"
tempfile = "3.13.0"
thiserror = "1.0.64"

[build-dependencies]
napi-build = "2.1.4"
